-- Set your context
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

-- CRITICAL: Set cost-saving auto-suspend
ALTER WAREHOUSE COMPUTE_WH SET AUTO_SUSPEND = 60;

-- Create your personal database
CREATE DATABASE IF NOT EXISTS TRUONGDO_DEV_DB
COMMENT = 'Personal development database';

-- Create schemas for the Medallion architecture
CREATE SCHEMA IF NOT EXISTS TRUONGDO_DEV_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS TRUONGDO_DEV_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS TRUONGDO_DEV_DB.GOLD;

-- Verify creation
SHOW SCHEMAS IN DATABASE TRUONGDO_DEV_DB;

USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA TPCH_SF1;

SELECT COUNT(*) FROM ORDERS;